# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

stages:
- stage: Build
  displayName: Build .Net Solution
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      fetchDepth: 0
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/CoinsManagerWebUI/*.csproj'
        feedsToUse: 'select'
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'vadsolodovnik'
        scannerMode: 'MSBuild'
        projectKey: 'vadsolodovnik_CoinsManagerWebUI'
        projectName: 'CoinsManagerWebUI'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-r linux-x64 --output $(build.artifactstagingdirectory)'
    - task: DotNetCoreCLI@2
      displayName: Unit test
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
    - task: SonarCloudAnalyze@1    
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
    - task: PublishBuildArtifacts@1
      displayName: Publish
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'